sudo: required
services:
  - docker
  
before_install:
  - sudo apt-get update
  - sudo apt-get install mysql-server-5.6
  - sudo apt-get install -y mongodb-org

script:
 - sudo service mongod status
